# Generated by Django 4.1.6 on 2023-03-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_no', models.CharField(max_length=5)),
                ('add_street', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=15)),
                ('add_state', models.CharField(max_length=15)),
                ('add_country', models.CharField(max_length=25)),
                ('add_zip', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=20)),
                ('agent_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=7)),
                ('agent_cno', models.CharField(max_length=10)),
                ('agent_dob', models.DateField()),
                ('agent_email', models.EmailField(max_length=254, unique=True)),
                ('agent_pswd', models.CharField(max_length=8)),
                ('agent_add', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.address')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bkg_date', models.DateField()),
                ('number_of_person', models.IntegerField()),
                ('price', models.CharField(max_length=6)),
                ('seat', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default=0, max_length=50)),
                ('customer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6)),
                ('customer_cno', models.CharField(max_length=10)),
                ('customer_dob', models.DateField(null=True)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_pswd', models.CharField(max_length=8)),
                ('customer_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.address')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eqry_name', models.CharField(max_length=20)),
                ('eqry_email', models.EmailField(max_length=254, unique=True)),
                ('eqry_remark', models.CharField(max_length=100)),
                ('eqry_type', models.CharField(max_length=10)),
                ('eqry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('C', 'Card'), ('U', 'UPI')], max_length=10)),
                ('payment_amt', models.IntegerField()),
                ('booking', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkg_title', models.CharField(max_length=30)),
                ('dep_date', models.DateField()),
                ('pkg_from', models.CharField(max_length=20)),
                ('pkg_to', models.CharField(max_length=20)),
                ('pkg_dec', models.TextField(max_length=255)),
                ('pkg_price', models.IntegerField()),
                ('pkg_days', models.IntegerField()),
                ('pkg_night', models.IntegerField()),
                ('tota_seats', models.IntegerField()),
                ('avil_seats', models.IntegerField()),
                ('pkg_type', models.CharField(choices=[('A', 'Adventure'), ('B', 'Beach'), ('R', 'Religious'), ('H', 'Heritage')], max_length=10)),
                ('pkg_status', models.BooleanField(default=True)),
                ('pkg_img', models.ImageField(default=1, upload_to='destination-2.jpg')),
                ('agent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=20)),
                ('hotel_type', models.CharField(max_length=20)),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=20)),
                ('hotel_add', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.address')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fb', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cl_time', models.TimeField()),
                ('cl_reason', models.CharField(max_length=255)),
                ('refund_st', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.packages'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('admin_cno', models.CharField(max_length=10)),
                ('admin_email', models.EmailField(max_length=254, null=True)),
                ('admin_dob', models.DateField(null=True)),
                ('admin_pswd', models.CharField(max_length=8)),
                ('admin_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.address')),
            ],
        ),
    ]
