# Generated by Django 4.1.6 on 2023-03-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
