# Generated by Django 4.0.4 on 2023-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_pswd',
            field=models.CharField(default='', max_length=8),
        ),
    ]
