# Generated by Django 4.1.6 on 2023-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_packages_avil_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add_city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_state',
            field=models.CharField(max_length=25),
        ),
    ]
