# Generated by Django 4.1.5 on 2023-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_id', models.IntegerField()),
                ('pkg_type', models.CharField(max_length=10)),
                ('pkg_title', models.CharField(max_length=10)),
                ('dep_date', models.DateField()),
                ('pkg_from', models.CharField(max_length=10)),
                ('pkg_to', models.CharField(max_length=10)),
                ('pkg_dec', models.CharField(max_length=100)),
                ('pkg_price', models.IntegerField()),
                ('pkg_days', models.IntegerField()),
                ('pkg_night', models.IntegerField()),
                ('tota_seats', models.IntegerField()),
                ('avil_seats', models.IntegerField()),
                ('pkg_status', models.BooleanField(default=True)),
            ],
        ),
    ]
