# Generated by Django 4.1.5 on 2023-03-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'ordering': ['-pkg_id']},
        ),
    ]
